# Generated by Django 5.0.6 on 2024-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='achieved_at',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
